skydev:
  restart: on_failure
  image: tstapler/skydev
  ports:
    - "8081:8081"
  volumes:
    - .:/code
  links:
    - postgres
postgres:
  image: postgres
  ports:
    - "5433:5432"
  environment:
    - POSTGRES_PASSWORD=pass
