name: SkyDev
version: 0.0.1
description: >
  An awesome tool for awesome developers. Enables collaboration between teams,
  easily viewable code versions, and instant pair programming
authors:
  - Josua Neil-Gonzales
  - Sambhav Srirama
  - Christopher Stapler
  - Tyler Stapler
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
transformers:
  - dart_to_js_script_rewriter