name: skydev
version: 0.0.1
description: >
  An awesome tool for awesome developers. Enables collaboration between teams,
  easily viewable code versions, and instant pair programming
authors:
  - Josua Gonzales-Neil<jgn@iastate.edu>
  - Sambhav Srirama <ssrirama@iastate.edu>
  - Christopher Stapler <cstapler@iastate.edu>
  - Tyler Stapler <tstapler@iastate.edu>
environment:
  sdk: ">=1.8.3 <2.0.0"
dependencies:
  react:
  http_server:
  dart_to_js_script_rewriter:
  bootstrap: "^3.3.4"
  polymer: ^1.0.0-rc.1
  browser: ^0.10.0
  polymer_elements:
  web_components: any
  reflectable:
  codemirror:

dev_dependencies:
  coverage: ^0.7.2
  dart_dev: ^1.0.0
  dart_style: <0.3.0
  dartdoc: ^0.4.0
  test: ^0.12.0
transformers:
- web_components:
    entry_points: web/login.html
- reflectable:
    entry_points: web/login.bootstrap.initialize.dart
- dart_to_js_script_rewriter:
- $dart2js:
    verbose: true
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.4
