name: todo
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/add-elements/
gist: https://gist.github.com/Sfshaza/65c90ff6b078c332d4b6
dartpad: https://dartpad.dartlang.org/65c90ff6b078c332d4b6
