name: skydev

version: 0.0.1

description: >
  An awesome tool for awesome developers. Enables collaboration between teams,
  easily viewable code versions, and instant pair programming
authors:
  - Josua Gonzales-Neil<jgn@iastate.edu>
  - Sambhav Srirama <ssrirama@iastate.edu>
  - Christopher Stapler <cstapler@iastate.edu>
  - Tyler Stapler <tstapler@iastate.edu>

environment:
  sdk: ">=1.13.0 <2.0.0"

dependencies:
  react: ^0.8.8
  http_server: ^0.9.5
  dart_to_js_script_rewriter: 1.0.1
  bootstrap: ^3.3.4
  browser: ^0.10.0
  reflectable: any
  codemirror: "0.4.0+5.8.0"
  postgresql: ^0.3.3
  trestle: ^0.7.0 
  args: any
  dbcrypt: ^0.2.1
  yaml: ^2.1.8
  bootjack: ^0.6.5
  query_string:
    git: https://github.com/kaisellgren/QueryString.git
  cookie: 0.0.4

transformers:
- $dart2js:
    verbose: true
