name: SkyDev
version: 0.0.1
description: >
  An awesome tool for awesome developers. Enables collaboration between teams,
  easily viewable code versions, and instant pair programming
authors:
  - Josua Gonzales-Neil<jgn@iastate.edu>
  - Sambhav Srirama <ssrirama@iastate.edu>
  - Christopher Stapler <cstapler@iastate.edu>
  - Tyler Stapler <tstapler@iastate.edu>
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  react:
  http_server:
  bootstrap: "^3.3.4"
  angular2: 2.0.0-beta.2
  polymer: 
  browser: ^0.10.0
  web_components: ^0.12.0
  reflectable: ^0.3.3
  codemirror:

dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
transformers:
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.4
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- polymer:
    entry_points: web/login.html
