---
- name: "Provision Database for SkyDev"
  hosts: localhost
  become: no
  handlers:
    - name: "seed database"
      script: "{{ playbook_dir }}/seed_db.sh"
  tasks:
    - name: "Create skydev database"
      postgresql_db:
        login_host="{{lookup('env','DB_HOST')}}"
        owner="{{lookup('env','DB_USER')}}"
        name="{{lookup('env','DB_NAME')}}"
        login_user="{{lookup('env','DB_USER')}}"
        login_password="{{lookup('env','DB_PASS')}}"
        state=present
        port="{{lookup('env','DB_PORT')}}"
      notify:
        - seed database
